name: 'Download Release Artifact'
description: 'Downloads artifact from the latest GitHub release'

inputs:
  pattern:
    description: 'Pattern to match the artifact'
    required: true
  download-path:
    description: 'Path where to download the artifact'
    required: true
    default: './downloads'
  extract-path:
    description: 'Path where to extract the artifact'
    required: true
    default: './extracted'
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  repository:
    description: 'Repository to download from (format: owner/repo)'
    required: false
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Create directories
      shell: bash
      run: |
        mkdir -p "${{ inputs.download-path }}"
        mkdir -p "${{ inputs.extract-path }}"

    - name: Get and Download Latest Release Asset
      shell: bash
      run: |
        cd "${{ inputs.download-path }}"
        
        echo "Current directory: $(pwd)"
        echo "Repository: ${{ inputs.repository }}"
        echo "Pattern to match: ${{ inputs.pattern }}"
        
        echo "=== Listing available releases ==="
        gh release list --repo ${{ inputs.repository }}
        
        echo "=== Attempting to download release ==="
        gh release download latest --repo ${{ inputs.repository }} --pattern "${{ inputs.pattern }}" --dir .
        
        echo "=== Downloaded files ==="
        ls -la
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Extract Archive
      shell: bash
      run: |
        cd "${{ inputs.download-path }}"
        echo "=== Extracting files ==="
        for f in *.tgz; do
          if [ -f "$f" ]; then
            echo "Extracting $f to ${{ inputs.extract-path }}"
            tar -xzf "$f" -C "${{ inputs.extract-path }}"
          else
            echo "No .tgz files found to extract"
          fi
        done
        
        echo "=== Extracted contents ==="
        ls -la "${{ inputs.extract-path }}"
