name: Create Release PR for API Client

on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download API Client Package
        uses: ./.github/actions/download-npm-package-build
        with:
          package-name: '@artandrey/api-client'
          output-dir: 'extracted'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug - List Downloaded Files
        run: |
          echo "=== Contents of extracted directory ==="
          ls -la ./extracted
          echo "=== Tree of extracted directory ==="
          tree ./extracted
      - name: Build API Client
        uses: ./.github/actions/build-api-client
      - name: Create Changeset
        id: changeset
        run: |
          cat << 'EOF' > .changeset/api-update-${{ github.run_number }}-${{ github.run_attempt }}.md
          ---
          "@artandrey/api-client": minor
          ---

          Api client updated
          EOF
      - name: Create Release PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: 'chore: version packages'
          title: 'chore: version packages'
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
