name: Release API Client

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup/action.yml
        with:
          workspaces: '["api-client", "backend"]'
      - name: Write API File
        run: pnpm run --filter backend api:write-file
      - name: Move API File
        run: |
          cp -f backend/api.json api-client/api.json
      - name: Build API Client
        run: pnpm run --filter api-client build
      - name: Create Changeset
        run: pnpm changeset add --package api-client --message "Api client release" --type minor
      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: 'chore: version packages'
          title: 'chore: version packages'
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
