name: Release API Client

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          workspaces: '["api-client", "backend"]'
      - name: Write API File
        run: pnpm run --filter backend api:write-file
      - name: Move API File
        run: |
          cp -f backend/api.json api-client/api.json
      - name: Build API Client
        run: pnpm run --filter api-client build
      - name: Create Changeset
        id: changeset
        run: |
          cat << 'EOF' > .changeset/api-update-${{ github.run_number }}-${{ github.run_attempt }}.md
          ---
          "@artandrey/api-client": minor
          ---

          Api client updated
          EOF
      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: 'chore: version packages'
          title: 'chore: version packages'
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
